# Generated by Django 6.0.2 on 2026-03-30 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_inventoryitem_delete_todo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_quantity", models.IntegerField()),
                ("new_quantity", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Adjustment"),
                            ("increase", "Stock Increase"),
                            ("decrease", "Stock Decrease"),
                            ("edit", "Edited via Form"),
                            ("created", "Item Created"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="todo.inventoryitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
