# Generated by Django 6.0.2 on 2026-02-10 08:40

from django.db import migrations
from django.contrib.auth.models import User


def remove_duplicate_emails(apps, schema_editor):
    """
    For each duplicate email, keep the user with the lowest ID and delete the others.
    """
    from django.db.models import Count
    from django.db.models.query_utils import Q
    
    # Find all emails that appear more than once
    duplicate_emails = (
        User.objects
        .values('email')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
        .exclude(email__isnull=True)
        .exclude(email='')
    )
    
    for duplicate in duplicate_emails:
        email = duplicate['email']
        # Get all users with this email, ordered by id
        users_with_email = User.objects.filter(email=email).order_by('id')
        
        # Keep the first user (lowest ID), delete the rest
        users_to_delete = users_with_email[1:]
        for user in users_to_delete:
            user.delete()


def reverse_duplicate_emails(apps, schema_editor):
    """
    This migration is not reversible as we've deleted data.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_emails, reverse_duplicate_emails),
    ]
