# Generated by Django 6.0.2 on 2026-02-10 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("authentication", "Profile")
    default_url = getattr(settings, "DEFAULT_PROFILE_IMAGE_URL", "")

    for user in User.objects.all().iterator():
        Profile.objects.get_or_create(
            user=user,
            defaults={"image_url": default_url},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_handle_duplicate_emails"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(blank=True, default="")),
                (
                    "image_public_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_profiles, migrations.RunPython.noop),
    ]
